### ISSUE TITLE
2.0 breaking changes?

### ISSUE THREAD

**Issue by FezVrasta** [iarna/in-publish#13]
I see you released a major version (2.x), what are the breaking changes? I can't find a changelog.

Thank you.

**Comment by jamesplease** [comment]
@FezVrasta , there was only one commit that changed the functionality between 1.1 and 2.0. You can check it out here: https://github.com/iarna/in-publish/commit/3ddf4225dfeb1b24c2c752f068b2c7f301dabc24 .

The tl;dr appears to be the addition of the `not-in-*` commands, which adds additional functionality to this lib described by the second half of the README.

Hope that helps!

**Comment by FezVrasta** [comment]
sure, thank you
