### ISSUE TITLE
Installing this on devDeps?

### ISSUE THREAD

**Issue by mightyiam** [iarna/in-publish#6]
Is there a specific reason that this is installed in `dependencies` vs. in `devDependencies`, please?

**Comment by scotthovestadt** [comment]
I'd also like an answer to this question.

I think based on what I know of the prepublish hook it should be in the regular dependencies but I'm not entirely sure.

**Comment by evocateur** [comment]
This package should _always_ be saved to `devDependencies`. There is **literally** no reason to save this in `dependencies`, as the `prepublish` lifecycle will never run when a package is installed as a dependency of another package.

If you're already on the `npm@4` happy path, [youv'e got choices](https://github.com/npm/npm/blob/latest/CHANGELOG.md#new-prepare-script-prepublish-deprecated-breaking).

**Comment by iarna** [comment]
Yeah, this is a doc bug– I've updated the README. Thanks for pointing it out.
